{% set name = "underworld" %}
{% set version = "2.16.4" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   url: https://github.com/underworldcode/underworld2/archive/refs/tags/v{{ version }}.tar.gz
   sha256: 70b2ccadc4917b82cf64819956acf2a0c8b69fcb3117188e801ef435da2c2f28
#  git_url : https://github.com/underworldcode/underworld2.git
#  git_rev : v2.16.x

build:
  skip: true  # [py<39 or win]
  number: 0
  script: PETSC_DIR=$PREFIX {{ PYTHON }} -m pip install . -vv
  ignore_run_exports:
    - mpi4py
    - hdf5
    - h5py
    - numpy

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ mpi }}
    - pkg-config
    - cmake
    - ninja
    - numpy<2

  host:
    - pip
    - setuptools
    - python <3.12
    - hdf5 =*=mpi*
    - h5py =*=mpi*
    - libxml2
    - numpy<2
    - petsc {{ petsc }}
    - {{ mpi }}
    - swig >=4.0.0

  run:
    - python
    - {{ pin_compatible('h5py') }}
    - {{ pin_compatible('hdf5') }}
    - {{ pin_compatible('numpy') }}
    - petsc {{ petsc }}
    - {{ mpi }}
    - mpi4py
    - pint
    - scipy
    - matplotlib-base

test:
  imports:
    - underworld

  requires:
    - python
    - pytest
    - matplotlib

  source_files:
    - docs/pytests
    - docs/user_guide
    - docs/examples

  commands:
    #    - pytest -vvv docs/pytests/test.py
    - python -X faulthandler -c "import underworld; underworld.mesh.FeMesh_Cartesian();"


about:
  home: https://github.com/underworldcode/underworld2
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LGPLv3.txt
  summary: "Geodynamics API"
  doc_url: https://underworld2.readthedocs.io
  dev_url: https://github.com/underworldcode/underworld2/tree/development

extra:
  recipe-maintainers:
    - julesghub
